spring:
  datasource:
    url: ${DB_URL}
    username: root
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PW}
  jwt:
    issuer: 'jwt'
    secret-key: ${SECRET_KEY}
    access-exp: 360000
    refresh-exp: 8640000
  upload:
    dir: ${UPLOAD_DIR}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 8080